spring:
  jpa:
    #    properties:
    #      hibernate:
    #        show_sql: true
    #        format_sql: true
    generate-ddl: true
    show-sql: 'true'
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    rest:
      base-path: /api
  sql:
    init:
      mode: always
      platform: h2
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    password: ''
logging:
  level:
    org:
      hibernate:
        type: trace
