spring:
  jpa:
    #    properties:
    #      hibernate:
    #        show_sql: true
    #        format_sql: true
    generate-ddl: true
    show-sql: 'true'
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    rest:
      detection-strategy: annotated
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    url: jdbc:hsqldb:mem:vecsesiot;DB_CLOSE_DELAY=-1
    password: ''
  mail:
    default-encoding: UTF-8
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 5df950739991e4
    password: d94a6b8397bb70
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false
  session:
    jdbc:
      initialize-schema: always
logging:
  level:
    org:
      hibernate:
        type: debug
  file:
    path: logs/
    name: logs/application.log
server:
  servlet:
    context-path: /api